# Generated by Django 5.2.8 on 2026-04-01 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0008_book_back_cover_image'),
        ('orders', '0004_add_coupon_fields'),
        ('organizations', '0001_initial'),
        ('users', '0006_create_lecteur_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Commission plateforme (%)')),
                ('delivery_base_fee', models.DecimalField(decimal_places=2, default=Decimal('1500'), max_digits=10, verbose_name='Frais de livraison de base (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration commissions',
                'verbose_name_plural': 'Configuration commissions',
            },
        ),
        migrations.CreateModel(
            name='DeliveryWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(limit_choices_to={'profile_type': 'LIVREUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_wallet', to='users.userprofile', verbose_name='Livreur')),
            ],
            options={
                'verbose_name': 'Portefeuille livreur',
                'verbose_name_plural': 'Portefeuilles livreurs',
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé par le vendeur'), ('PREPARING', 'En préparation'), ('READY', 'Prêt pour livraison'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_agent', models.ForeignKey(blank=True, limit_choices_to={'profile_type': 'LIVREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to='users.userprofile', verbose_name='Livreur assigné')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='Commande parente')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='organizations.organization', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Sous-commande',
                'verbose_name_plural': 'Sous-commandes',
                'ordering': ['-created_at'],
                'unique_together': {('order', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Solde (FCFA)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total gagné (FCFA)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total retiré (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='organizations.organization', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Portefeuille vendeur',
                'verbose_name_plural': 'Portefeuilles vendeurs',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT_SALE', 'Crédit — Vente'), ('DEBIT_COMMISSION', 'Débit — Commission plateforme'), ('DEBIT_WITHDRAWAL', 'Débit — Retrait'), ('CREDIT_REFUND', 'Crédit — Remboursement')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.suborder')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.vendorwallet')),
            ],
            options={
                'verbose_name': 'Transaction portefeuille',
                'verbose_name_plural': 'Transactions portefeuille',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix vendeur (FCFA)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'origine (FCFA)")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('condition', models.CharField(choices=[('NEW', 'Neuf'), ('USED_GOOD', 'Bon état'), ('USED_FAIR', 'Acceptable')], default='NEW', max_length=20, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='books.book', verbose_name='Livre')),
                ('vendor', models.ForeignKey(limit_choices_to={'org_type__in': ['MAISON_EDITION', 'LIBRAIRIE']}, on_delete=django.db.models.deletion.CASCADE, related_name='book_listings', to='organizations.organization', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Offre vendeur',
                'verbose_name_plural': 'Offres vendeurs',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['book', 'is_active'], name='marketplace_book_id_ba566e_idx'), models.Index(fields=['vendor', 'is_active'], name='marketplace_vendor__84d048_idx'), models.Index(fields=['price'], name='marketplace_price_df2522_idx')],
                'unique_together': {('book', 'vendor')},
            },
        ),
    ]
