# Generated by Django 5.2.8 on 2026-04-02 00:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='service_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Commission services (%)'),
        ),
    ]
