# Generated by Django 6.0.3 on 2026-04-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrate',
            name='country',
            field=models.CharField(choices=[('GA', 'Gabon'), ('CM', 'Cameroun'), ('SN', 'Sénégal'), ('CI', "Côte d'Ivoire"), ('CD', 'RD Congo'), ('CG', 'Congo'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('GN', 'Guinée'), ('NE', 'Niger'), ('TD', 'Tchad'), ('BJ', 'Bénin'), ('TG', 'Togo'), ('MR', 'Mauritanie'), ('GQ', 'Guinée équatoriale'), ('CF', 'Centrafrique'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('TZ', 'Tanzanie'), ('UG', 'Ouganda'), ('RW', 'Rwanda'), ('ET', 'Éthiopie'), ('ZA', 'Afrique du Sud'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('MG', 'Madagascar'), ('AO', 'Angola'), ('MZ', 'Mozambique'), ('ZW', 'Zimbabwe'), ('ZM', 'Zambie'), ('MW', 'Malawi'), ('SL', 'Sierra Leone'), ('LR', 'Liberia'), ('GM', 'Gambie'), ('GW', 'Guinée-Bissau'), ('CV', 'Cap-Vert'), ('ST', 'São Tomé-et-Príncipe'), ('BI', 'Burundi'), ('DJ', 'Djibouti'), ('ER', 'Érythrée'), ('SO', 'Somalie'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('LY', 'Libye'), ('LS', 'Lesotho'), ('SZ', 'Eswatini'), ('BW', 'Botswana'), ('NA', 'Namibie'), ('MU', 'Maurice'), ('SC', 'Seychelles'), ('KM', 'Comores')], max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='deliveryrate',
            name='currency',
            field=models.CharField(choices=[('XAF', 'FCFA (CEMAC)'), ('XOF', 'FCFA (UEMOA)'), ('NGN', 'Naira nigérian'), ('KES', 'Shilling kényan'), ('GHS', 'Cedi ghanéen'), ('ZAR', 'Rand sud-africain'), ('MAD', 'Dirham marocain'), ('EGP', 'Livre égyptienne'), ('RWF', 'Franc rwandais'), ('TZS', 'Shilling tanzanien'), ('UGX', 'Shilling ougandais'), ('ETB', 'Birr éthiopien'), ('CDF', 'Franc congolais'), ('AOA', 'Kwanza angolais'), ('MZN', 'Metical mozambicain'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='XAF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
