# Generated by Django 5.2.8 on 2026-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_account_deletion_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prêt depuis'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='unassigned_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Alerte livreur envoyée'),
        ),
    ]
