# Generated by Django 6.0.3 on 2026-04-13 03:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_template_and_coupon_v2'),
        ('marketplace', '0009_suborder_attempted_delivery_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_orders', to='coupons.coupon', verbose_name='Coupon appliqué'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction coupon (FCFA)'),
        ),
    ]
