# Generated by Django 5.2.8 on 2026-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_suborder_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé par le vendeur'), ('PREPARING', 'En préparation'), ('READY', 'Prêt pour livraison'), ('SHIPPED', 'Expédié'), ('ATTEMPTED', 'Tentative de livraison échouée'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Termine'), ('FAILED', 'Echoue'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
