# Generated by Django 5.2.8 on 2026-04-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_back_cover_image'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'Général'), ('ROMAN', 'Romans'), ('POESIE', 'Poésie'), ('ESSAI', 'Essais & Non-fiction'), ('JEUNESSE', 'Littérature jeunesse'), ('SF_FANTASY', 'Science-fiction & Fantasy'), ('POLAR', 'Policier & Thriller'), ('BD_MANGA', 'BD & Manga'), ('CLASSIQUES', 'Classiques'), ('AFRICAIN', 'Littérature africaine'), ('DEVELOPPEMENT', 'Développement personnel'), ('AUTRE', 'Autre')], default='GENERAL', max_length=20, verbose_name='Catégorie / Thème'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/covers/', verbose_name='Photo de couverture'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='current_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_clubs', to='books.book', verbose_name='Livre en cours de discussion'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['FR', 'EN']", verbose_name='Langues du club'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='meeting_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Hebdomadaire'), ('BIWEEKLY', 'Bimensuel'), ('MONTHLY', 'Mensuel'), ('FLEXIBLE', 'Flexible')], default='MONTHLY', max_length=20, verbose_name='Fréquence des échanges'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='rules',
            field=models.TextField(blank=True, help_text='Charte, code de conduite, attentes envers les membres.', verbose_name='Règles du club'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['afrique', 'femmes-auteurs', 'poésie']", verbose_name='Tags / Mots-clés'),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='books.book', verbose_name='Livre fondateur (legacy)'),
        ),
    ]
