# Generated by Django 5.2.8 on 2026-04-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_bookclub_category_bookclub_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='category',
            field=models.JSONField(blank=True, default=list, help_text="Liste de thèmes. Ex: ['ROMAN', 'AFRICAIN']", verbose_name='Catégories / Thèmes'),
        ),
    ]
