# Generated by Django 5.2.8 on 2026-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_bookclub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='clubs/messages/', verbose_name='Pièce jointe (image, fichier, note vocale)'),
        ),
        migrations.AddField(
            model_name='bookclubmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='bookclubmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Texte'), ('VOICE', 'Note vocale'), ('IMAGE', 'Image'), ('FILE', 'Fichier')], default='TEXT', max_length=10, verbose_name='Type de message'),
        ),
        migrations.AddField(
            model_name='bookclubmessage',
            name='voice_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée note vocale (secondes)'),
        ),
        migrations.AlterField(
            model_name='bookclubmessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Message texte'),
        ),
    ]
