# Generated by Django 5.2.8 on 2026-04-08 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_author_user'),
        ('social', '0004_bookclubmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note de 1 à 5, utilisée pour les avis plateforme.', null=True, verbose_name='Note (1-5)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TEXT', 'Texte'), ('REVIEW', 'Avis partagé'), ('RECOMMENDATION', 'Recommandation'), ('NEWS', 'Actualité'), ('PLATFORM_REVIEW', 'Avis plateforme')], default='TEXT', max_length=20, verbose_name='Type de publication'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='social_post_post_ty_585d5d_idx'),
        ),
    ]
