# Generated by Django 5.2.8 on 2026-04-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_account_deletion_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la dernière fois que le membre a consulté le chat.', null=True, verbose_name='Dernière lecture'),
        ),
    ]
