# Generated by Django 5.2.8 on 2026-04-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_add_last_read_at_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='bookclubmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
