# Generated by Django 5.2.8 on 2026-04-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_add_message_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmembership',
            name='reading_progress',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage de progression dans le livre en cours du club (0-100).', verbose_name='Progression de lecture (%)'),
        ),
    ]
