# Generated by Django 5.2.8 on 2026-04-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_account_deletion_set_null'),
        ('social', '0010_add_reading_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vote pour le prochain livre', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Clos')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='social.bookclub', verbose_name='Club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote de club',
                'verbose_name_plural': 'Votes de club',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='books.book', verbose_name='Livre')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.bookpoll', verbose_name='Vote')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option de vote',
                'unique_together': {('poll', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.bookpolloption', verbose_name='Option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='Votant')),
            ],
            options={
                'verbose_name': 'Vote',
                'unique_together': {('option', 'user')},
            },
        ),
    ]
