# Generated by Django 5.2.8 on 2026-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_add_book_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubmessage',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Épinglé'),
        ),
    ]
