# Generated by Django 5.2.8 on 2026-04-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_CREATED', 'Commande créée'), ('ORDER_PAID', 'Paiement confirmé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('SUBORDER_STATUS', 'Statut commande mis à jour'), ('ORDER_DELIVERED', 'Commande livrée'), ('DELIVERY_ATTEMPTED', 'Tentative de livraison'), ('ORG_INVITATION', 'Invitation organisation'), ('MANUSCRIPT_STATUS', 'Statut manuscrit')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
