# Generated by Django 6.0.3 on 2026-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Commande créée'), ('ORDER_PAID', 'Paiement confirmé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('SUBORDER_STATUS', 'Statut commande mis à jour'), ('ORDER_DELIVERED', 'Commande livrée'), ('DELIVERY_ATTEMPTED', 'Tentative de livraison'), ('ORG_INVITATION', 'Invitation organisation'), ('MANUSCRIPT_STATUS', 'Statut manuscrit'), ('COUPON_RECEIVED', 'Coupon reçu'), ('COUPON_REVOKED', 'Coupon révoqué')], max_length=30, verbose_name='Type'),
        ),
    ]
