# Generated by Django 5.2.8 on 2026-04-02 00:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0008_book_back_cover_image'),
        ('manuscripts', '0004_manuscript_submitter'),
        ('organizations', '0001_initial'),
        ('users', '0006_create_lecteur_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix proposé (FCFA)')),
                ('turnaround_days', models.PositiveIntegerField(verbose_name='Délai (jours)')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devis de service',
                'verbose_name_plural': 'Devis de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CORRECTION', 'Correction'), ('ILLUSTRATION', 'Illustration'), ('LAYOUT', 'Mise en page'), ('REVIEW', 'Révision'), ('APPROVED', 'Approuvé'), ('PRINTING', 'Impression'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_projects', to='books.book', verbose_name='Livre')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_projects', to='manuscripts.manuscript', verbose_name='Manuscrit')),
                ('organization', models.ForeignKey(limit_choices_to={'org_type': 'MAISON_EDITION'}, on_delete=django.db.models.deletion.CASCADE, related_name='editorial_projects', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Projet éditorial',
                'verbose_name_plural': 'Projets éditoriaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_specs', models.JSONField(blank=True, default=dict, verbose_name='Spécifications de format')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire (FCFA)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total (FCFA)')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUOTED', 'Devis reçu'), ('CONFIRMED', 'Confirmée'), ('PRINTING', 'En impression'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to='books.book', verbose_name='Livre')),
                ('printer', models.ForeignKey(limit_choices_to={'org_type': 'IMPRIMERIE'}, on_delete=django.db.models.deletion.CASCADE, related_name='print_requests_received', to='organizations.organization', verbose_name='Imprimerie')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests', to='services.editorialproject', verbose_name='Projet éditorial')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('requester_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_requests_sent', to='organizations.organization', verbose_name='Organisation demandeuse')),
            ],
            options={
                'verbose_name': "Demande d'impression",
                'verbose_name_plural': "Demandes d'impression",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Solde (FCFA)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total gagné (FCFA)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total retiré (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(limit_choices_to={'profile_type__in': ['CORRECTEUR', 'ILLUSTRATEUR', 'TRADUCTEUR']}, on_delete=django.db.models.deletion.CASCADE, related_name='professional_wallet', to='users.userprofile', verbose_name='Professionnel')),
            ],
            options={
                'verbose_name': 'Portefeuille professionnel',
                'verbose_name_plural': 'Portefeuilles professionnels',
            },
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('CORRECTION', 'Correction'), ('ILLUSTRATION', 'Illustration'), ('TRANSLATION', 'Traduction'), ('COVER_DESIGN', 'Conception de couverture'), ('LAYOUT', 'Mise en page'), ('PROOFREADING', 'Relecture')], max_length=20, verbose_name='Type de service')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_type', models.CharField(choices=[('PER_PAGE', 'Par page'), ('PER_WORD', 'Par mot'), ('PER_PROJECT', 'Par projet'), ('HOURLY', "À l'heure")], max_length=20, verbose_name='Type de tarification')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de base (FCFA)')),
                ('turnaround_days', models.PositiveIntegerField(verbose_name='Délai (jours)')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='Langues')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Genres')),
                ('portfolio_samples', models.JSONField(blank=True, default=list, verbose_name='Exemples de portfolio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'profile_type__in': ['CORRECTEUR', 'ILLUSTRATEUR', 'TRADUCTEUR']}, on_delete=django.db.models.deletion.CASCADE, related_name='service_listings', to='users.userprofile', verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Offre de service',
                'verbose_name_plural': 'Offres de services',
                'ordering': ['service_type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'En révision'), ('REVISION', 'Révision demandée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (FCFA)')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Commission plateforme (FCFA)')),
                ('deliverable_file', models.FileField(blank=True, null=True, upload_to='services/deliverables/', verbose_name='Fichier livrable')),
                ('deadline', models.DateTimeField(verbose_name='Date limite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='users.userprofile', verbose_name='Prestataire')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.servicequote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Commande de service',
                'verbose_name_plural': 'Commandes de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CORRECTION', 'Correction'), ('ILLUSTRATION', 'Illustration'), ('COVER_DESIGN', 'Conception de couverture'), ('LAYOUT', 'Mise en page'), ('PROOFREADING', 'Relecture'), ('TRANSLATION', 'Traduction')], max_length=20, verbose_name='Type de tâche')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'En révision'), ('DONE', 'Terminée')], default='TODO', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.userprofile', verbose_name='Assigné à')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='services.editorialproject', verbose_name='Projet')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='services.serviceorder', verbose_name='Commande de service')),
            ],
            options={
                'verbose_name': 'Tâche de projet',
                'verbose_name_plural': 'Tâches de projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT_SERVICE', 'Crédit — Service'), ('DEBIT_COMMISSION', 'Débit — Commission plateforme'), ('DEBIT_WITHDRAWAL', 'Débit — Retrait')], max_length=30, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.professionalwallet', verbose_name='Portefeuille')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='services.serviceorder', verbose_name='Commande de service')),
            ],
            options={
                'verbose_name': 'Transaction portefeuille professionnel',
                'verbose_name_plural': 'Transactions portefeuille professionnel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Exigences')),
                ('file', models.FileField(blank=True, null=True, upload_to='services/requests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='Fichier joint')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de mots')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget minimum (FCFA)')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget maximum (FCFA)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('QUOTED', 'Devis envoyé'), ('ACCEPTED', 'Acceptée'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'En révision'), ('REVISION', 'Révision demandée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.servicelisting', verbose_name='Offre de service')),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='users.userprofile', verbose_name='Profil prestataire')),
            ],
            options={
                'verbose_name': 'Demande de service',
                'verbose_name_plural': 'Demandes de services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicequote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.servicerequest', verbose_name='Demande'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.servicerequest', verbose_name='Demande'),
        ),
    ]
