# Generated by Django 5.2.8 on 2026-04-08 10:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicelisting_organization_serviceproviderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequote',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Ex: 50% à la commande, 50% à la livraison.', max_length=50, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='revision_rounds',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de tours de révision inclus dans le prix.', verbose_name='Révisions incluses'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='scope_of_work',
            field=models.TextField(blank=True, help_text='Détail de ce qui est inclus dans le devis.', verbose_name='Périmètre de la prestation'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message / conditions'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix total proposé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='servicequote',
            name='turnaround_days',
            field=models.PositiveIntegerField(verbose_name='Délai de livraison (jours)'),
        ),
    ]
