# Generated by Django 5.2.8 on 2026-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_quote_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequote',
            name='exclusions',
            field=models.TextField(blank=True, help_text="Ce qui n'est PAS inclus dans le devis.", verbose_name='Exclusions'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='methodology',
            field=models.TextField(blank=True, help_text='Approche, outils utilisés, processus de travail.', verbose_name='Méthodologie de travail'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='milestones',
            field=models.JSONField(blank=True, default=list, help_text='Liste de jalons: [{"title":"...", "days":..., "deliverable":"..."}]', verbose_name='Jalons / sprints'),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='reporting_frequency',
            field=models.CharField(blank=True, help_text='Ex: hebdomadaire, bi-hebdomadaire, à chaque jalon.', max_length=30, verbose_name='Fréquence de reporting'),
        ),
    ]
