# Generated by Django 5.2.8 on 2026-04-09 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0007_add_dqe_quote_system'),
        ('organizations', '0003_extend_org_fields'),
        ('services', '0004_add_quote_methodology'),
        ('users', '0012_add_cover_image_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('title', models.CharField(max_length=300, verbose_name='Objet du devis')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total HT (FCFA)')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('AMOUNT', 'Montant fixe')], default='PERCENT', max_length=10, verbose_name='Type de remise')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage (ex: 5.00) ou montant fixe en FCFA.', max_digits=10, verbose_name='Valeur de la remise')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant de la remise (FCFA)')),
                ('subtotal_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total après remise (FCFA)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='0 si exonéré. 18% par défaut au Gabon.', max_digits=5, verbose_name='Taux TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TVA (FCFA)')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TTC (FCFA)')),
                ('payment_schedule', models.JSONField(blank=True, default=list, help_text='[{"label": "À la commande", "percent": 40, "amount": 1290495}, ...]', verbose_name='Échéancier de paiement')),
                ('delivery_days', models.PositiveIntegerField(default=30, verbose_name='Délai de livraison (jours ouvrés)')),
                ('validity_days', models.PositiveIntegerField(default=30, verbose_name='Validité du devis (jours)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('revision_rounds', models.PositiveIntegerField(default=1, verbose_name='Révisions incluses')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / conditions particulières')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepté le')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Refusé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dqe_quotes', to='manuscripts.manuscript', verbose_name='Manuscrit')),
                ('provider_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_quotes', to='organizations.organization', verbose_name='Organisation émettrice')),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_quotes', to='users.userprofile', verbose_name='Profil prestataire')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dqe_quotes', to='services.servicerequest', verbose_name='Demande de service')),
            ],
            options={
                'verbose_name': 'Devis (DQE)',
                'verbose_name_plural': 'Devis (DQE)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lot')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total du lot (FCFA)')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='services.quote', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Lot de devis',
                'verbose_name_plural': 'Lots de devis',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('unit', models.CharField(choices=[('PAGE', 'Page'), ('MOT', 'Mot'), ('EXEMPLAIRE', 'Exemplaire'), ('FORFAIT', 'Forfait'), ('HEURE', 'Heure'), ('JOUR', 'Jour'), ('FEUILLE', 'Feuille'), ('PLANCHE', 'Planche'), ('CARACTERE', 'Caractère')], default='FORFAIT', max_length=20, verbose_name='Unité')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total (FCFA)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.quotelot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Vide = modèle global Frollot, disponible pour tous.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_templates', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Modèle de devis',
                'verbose_name_plural': 'Modèles de devis',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='services.quotetemplate', verbose_name='Modèle utilisé'),
        ),
        migrations.CreateModel(
            name='QuoteTemplateLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lot')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='services.quotetemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Lot type',
                'verbose_name_plural': 'Lots types',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('unit', models.CharField(choices=[('PAGE', 'Page'), ('MOT', 'Mot'), ('EXEMPLAIRE', 'Exemplaire'), ('FORFAIT', 'Forfait'), ('HEURE', 'Heure'), ('JOUR', 'Jour'), ('FEUILLE', 'Feuille'), ('PLANCHE', 'Planche'), ('CARACTERE', 'Caractère')], default='FORFAIT', max_length=20, verbose_name='Unité')),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité par défaut')),
                ('default_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix unitaire par défaut (FCFA)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.quotetemplatelot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Poste type',
                'verbose_name_plural': 'Postes types',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['reference'], name='services_qu_referen_e2a2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='services_qu_status_bfcddd_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['-created_at'], name='services_qu_created_35102e_idx'),
        ),
    ]
