# Generated by Django 6.0.3 on 2026-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_author_purchase_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='last_revision_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motif de la dernière révision'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Révisions effectuées'),
        ),
    ]
