# Generated by Django 6.0.3 on 2026-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_revision_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='auto_complete_notified',
            field=models.PositiveIntegerField(default=0, help_text='0 = aucun, 1 = J-7 envoyé, 2 = J-1 envoyé.', verbose_name='Préavis auto-complétion envoyés'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage du dernier upload de livrable. Sert de base pour l'auto-complétion à 14 jours.", null=True, verbose_name='Livrable envoyé le'),
        ),
    ]
