# Generated by Django 6.0.3 on 2026-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_account_deletion_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('REVISION_REQUESTED', 'Révision demandée'), ('SUPERSEDED', 'Remplacé par une révision'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
    ]
