# Generated by Django 6.0.3 on 2026-04-13 09:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_coupon_provider_profile'),
        ('services', '0011_add_superseded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='coupons.coupon', verbose_name='Coupon appliqué'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Réduction coupon (FCFA)'),
        ),
    ]
