# Generated by Django 5.2.8 on 2026-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceorder_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialproject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('CORRECTION', 'Correction'), ('ILLUSTRATION', 'Illustration'), ('LAYOUT', 'Mise en page'), ('REVIEW', 'Révision'), ('APPROVED', 'Approuvé'), ('PRINTING', 'Impression'), ('PUBLISHED', 'Publié')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUOTED', 'Devis reçu'), ('CONFIRMED', 'Confirmée'), ('PRINTING', 'En impression'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'En révision'), ('REVISION', 'Révision demandée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('QUOTED', 'Devis envoyé'), ('ACCEPTED', 'Acceptée'), ('IN_PROGRESS', 'En cours'), ('REVIEW', 'En révision'), ('REVISION', 'Révision demandée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], db_index=True, default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
    ]
