# Generated by Django 5.2.8 on 2025-12-02 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +243XXXXXXXXX (requis pour Mobile Money)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres. Format accepté: +243123456789 ou 0123456789', regex='^\\+?\\d{8,15}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
