# Generated by Django 5.2.14 on 2026-05-26 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +243XXXXXXXXX (requis pour Mobile Money)', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format accepte : +241XXXXXXXX (international) ou 0XXXXXXXX (local, 8-10 chiffres).', regex='^(\\+[1-9]\\d{7,14}|0\\d{7,9})$')], verbose_name='Numéro de téléphone'),
        ),
    ]
