# Generated by Django 5.2.8 on 2026-04-01 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('LECTEUR', 'Lecteur'), ('AUTEUR', 'Auteur'), ('CORRECTEUR', 'Correcteur / Relecteur'), ('ILLUSTRATEUR', 'Illustrateur / Graphiste'), ('TRADUCTEUR', 'Traducteur'), ('LIVREUR', 'Livreur indépendant')], max_length=20, verbose_name='Type de profil')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug (URL publique)')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie / Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil actif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié par la plateforme')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Ex: zones de couverture (livreur), langues (traducteur), tarifs (correcteur)...', verbose_name='Données spécifiques au profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['user', 'profile_type'],
                'unique_together': {('user', 'profile_type')},
            },
        ),
    ]
