# Generated by Django 5.2.8 on 2026-04-02 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_token_version_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA TOTP activé'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Secret TOTP'),
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Clé de session')),
                ('device_name', models.CharField(max_length=200, verbose_name="Nom de l'appareil")),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Ordinateur'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablette'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=20, verbose_name="Type d'appareil")),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session active',
                'verbose_name_plural': 'Sessions actives',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Hash du code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_backup_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code de secours TOTP',
                'verbose_name_plural': 'Codes de secours TOTP',
            },
        ),
        migrations.CreateModel(
            name='TOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Challenge TOTP',
                'verbose_name_plural': 'Challenges TOTP',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_used', models.EmailField(max_length=254, verbose_name='Email utilisé')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Info appareil')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échoué'), ('TOTP_PENDING', 'En attente TOTP'), ('BLOCKED', 'Bloqué')], max_length=20, verbose_name='Statut')),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_PASSWORD', 'Mot de passe invalide'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('INVALID_TOTP', 'Code TOTP invalide'), ('UNVERIFIED_EMAIL', 'Email non vérifié')], max_length=30, null=True, verbose_name="Raison de l'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_login_user_id_fe6b3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('GITHUB', 'GitHub')], max_length=20, verbose_name='Fournisseur')),
                ('provider_uid', models.CharField(max_length=200, verbose_name='UID fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte social',
                'verbose_name_plural': 'Comptes sociaux',
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
