# Generated by Django 5.2.8 on 2026-04-02 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_totp_enabled_user_totp_secret_activesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('GITHUB', 'GitHub')], max_length=20, verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='OAuthExchangeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('session_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_exchange_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_oauth_exchange_token',
            },
        ),
    ]
