# Generated by Django 5.2.8 on 2026-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_socialaccount_provider_oauthexchangetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_response_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps de réponse moyen (jours)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_projects',
            field=models.IntegerField(default=0, verbose_name='Projets terminés'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
    ]
