# Generated by Django 5.2.8 on 2026-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_avg_rating_userprofile_avg_response_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Photo distincte de l'avatar utilisateur, utilisée sur la vitrine publique.", null=True, upload_to='profiles/photos/', verbose_name='Photo professionnelle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web / Portfolio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('LECTEUR', 'Lecteur'), ('AUTEUR', 'Auteur'), ('EDITEUR', 'Éditeur'), ('CORRECTEUR', 'Correcteur / Relecteur'), ('ILLUSTRATEUR', 'Illustrateur / Graphiste'), ('TRADUCTEUR', 'Traducteur'), ('LIVREUR', 'Livreur indépendant')], max_length=20, verbose_name='Type de profil'),
        ),
    ]
