# Generated by Django 5.2.8 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_editeur_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Bannière affichée en haut de la vitrine publique du professionnel.', null=True, upload_to='profiles/covers/', verbose_name='Image de couverture'),
        ),
    ]
