# Generated by Django 6.0.3 on 2026-04-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_cover_image_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage côté serveur au moment de l'inscription.", null=True, verbose_name="Date d'acceptation des CGU"),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, default='', help_text='Date de publication des CGU acceptées (ex: 2026-04-11).', max_length=20, verbose_name='Version des CGU acceptées'),
        ),
    ]
