# Generated by Django 5.2.8 on 2026-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_account_deletion_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('LECTEUR', 'Lecteur'), ('AUTEUR', 'Auteur'), ('EDITEUR', 'Éditeur'), ('CORRECTEUR', 'Correcteur / Relecteur'), ('ILLUSTRATEUR', 'Illustrateur / Graphiste'), ('TRADUCTEUR', 'Traducteur'), ('LIVREUR', 'Livreur indépendant')], db_index=True, max_length=20, verbose_name='Type de profil'),
        ),
    ]
