# Generated by Django 5.2.8 on 2026-03-07 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_free_threshold', models.DecimalField(decimal_places=2, default=25000, help_text='Montant minimum du panier pour la livraison gratuite', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil livraison gratuite (FCFA)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=2000, help_text='Frais si le panier est inférieur au seuil', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais de livraison (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
