# Generated by Django 5.2.8 on 2025-12-03 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre du manuscrit')),
                ('author_name', models.CharField(max_length=200, verbose_name="Nom de l'auteur")),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('file', models.FileField(upload_to='manuscripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='Fichier manuscrit')),
                ('description', models.TextField(verbose_name='Description du manuscrit')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWING', "En cours d'examen"), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
            ],
            options={
                'verbose_name': 'Manuscrit',
                'verbose_name_plural': 'Manuscrits',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
