# Generated by Django 5.2.8 on 2026-03-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_add_manuscript_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='terms_accepted',
            field=models.BooleanField(verbose_name='Conditions acceptées'),
        ),
    ]
