# Generated by Django 6.0.3 on 2026-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_alter_manuscript_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprime'),
        ),
    ]
