# Generated by Django 5.2.8 on 2026-04-02 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_alter_manuscript_terms_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_manuscripts', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
    ]
