# Generated by Django 5.2.8 on 2026-04-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_manuscript_submitter'),
        ('organizations', '0002_organization_accepted_genres_organization_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='is_open_market',
            field=models.BooleanField(default=False, help_text="Si vrai, visible par toutes les maisons d'édition acceptant ce genre.", verbose_name='Marché ouvert'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='target_organization',
            field=models.ForeignKey(blank=True, help_text="Maison d'édition ciblée pour cette soumission. Vide = soumission générale.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_manuscripts', to='organizations.organization', verbose_name='Organisation cible'),
        ),
    ]
