# Generated by Django 5.2.14 on 2026-05-26 22:09

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='manuscripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])], verbose_name='Fichier manuscrit'),
        ),
    ]
