# Generated by Django 5.2.8 on 2026-04-05 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_manuscript_is_open_market_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text="Feedback envoyé à l'auteur en cas de refus.", verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'examen"),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manuscripts', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
    ]
