# Generated by Django 5.2.8 on 2026-04-09 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_add_review_fields'),
        ('organizations', '0003_extend_org_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['status'], name='manuscripts_status_7ba2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['submitter'], name='manuscripts_submitt_6fc47e_idx'),
        ),
        migrations.AddIndex(
            model_name='manuscript',
            index=models.Index(fields=['-submitted_at'], name='manuscripts_submitt_fe5690_idx'),
        ),
    ]
