import api from './api';

const aiService = {
  getQuota: () => api.get('/ai/quota/').then(r => r.data),
  categorize: (data) => api.post('/ai/categorize/', data).then(r => r.data),
  generateDescription: (data) => api.post('/ai/generate-description/', data).then(r => r.data),
  generateBackCover: (data) => api.post('/ai/generate-back-cover/', data).then(r => r.data),
  summarizeBook: (bookId) => api.post('/ai/summarize-book/', { book_id: bookId }).then(r => r.data),
  synthesizeReviews: (bookId) => api.post('/ai/synthesize-reviews/', { book_id: bookId }).then(r => r.data),
  analyzeManuscript: (data) => api.post('/ai/analyze-manuscript/', data).then(r => r.data),
  semanticSearch: (query) => api.post('/ai/semantic-search/', { query }).then(r => r.data),
  recommend: (count = 8) => api.post('/ai/recommend/', { count }).then(r => r.data),
  crossSell: (bookIds) => api.post('/ai/cross-sell/', { book_ids: bookIds }).then(r => r.data),
  moderate: (message, clubName) => api.post('/ai/moderate/', { message, club_name: clubName }).then(r => r.data),
  summarizeDiscussion: (clubId, lastN = 50) => api.post('/ai/summarize-discussion/', { club_id: clubId, last_n_messages: lastN }).then(r => r.data),
  discussionQuestions: (bookId, checkpoint) => api.post('/ai/discussion-questions/', { book_id: bookId, checkpoint_label: checkpoint || '' }).then(r => r.data),
  detectSpoiler: (reviewText, bookTitle) => api.post('/ai/detect-spoiler/', { review_text: reviewText, book_title: bookTitle || '' }).then(r => r.data),
  summarizeMeeting: (sessionId) => api.post('/ai/summarize-meeting/', { session_id: sessionId }).then(r => r.data),
  detectInactive: (clubId, days = 14) => api.post('/ai/detect-inactive/', { club_id: clubId, days_threshold: days }).then(r => r.data),
  recommendPublishers: (manuscriptId) => api.post('/ai/recommend-publishers/', { manuscript_id: manuscriptId }).then(r => r.data),
  similarManuscripts: (manuscriptId) => api.post('/ai/similar-manuscripts/', { manuscript_id: manuscriptId }).then(r => r.data),
  estimateQuote: (data) => api.post('/ai/estimate-quote/', data).then(r => r.data),
  recommendClubs: (count = 5) => api.post('/ai/recommend-clubs/', { count }).then(r => r.data),
  predictLateReturn: (orgId) => api.post('/ai/predict-late-return/', { org_id: orgId }).then(r => r.data),
  smartCouponTargeting: (segment, count = 10) => api.post('/ai/smart-coupon-targeting/', { segment, count }).then(r => r.data),
  suggestAuthors: (count = 6) => api.post('/ai/suggest-authors/', { count }).then(r => r.data),
  activitySummary: () => api.post('/ai/activity-summary/').then(r => r.data),
  dashboardHelp: (page) => api.post('/ai/dashboard-help/', { page }).then(r => r.data),
  personalizedNewsletter: (email) => api.post('/ai/personalized-newsletter/', { subscriber_email: email }).then(r => r.data),
  wishlistAlerts: () => api.post('/ai/wishlist-alerts/').then(r => r.data),
  vendorTrends: () => api.post('/ai/vendor-trends/').then(r => r.data),
  predictStock: (bookId, orgId) => api.post('/ai/predict-stock/', { book_id: bookId, ...(orgId ? { org_id: orgId } : {}) }).then(r => r.data),
  libraryAcquisitions: (orgId) => api.post('/ai/library-acquisitions/', { org_id: orgId }).then(r => r.data),
  libraryRecommend: (orgId, count = 6) => api.post('/ai/library-recommend/', { org_id: orgId, count }).then(r => r.data),
  suggestPrice: (bookId) => api.post('/ai/suggest-price/', { book_id: bookId }).then(r => r.data),
  chatbot: (message, contextPage, history = []) => api.post('/ai/chatbot/', { message, context_page: contextPage || '', history }).then(r => r.data),
  classifyContact: (data) => api.post('/ai/classify-contact/', data).then(r => r.data),
  generateBio: () => api.post('/ai/generate-bio/').then(r => r.data),
};

export default aiService;
