# Generated by Django 5.2.8 on 2026-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_shipping_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MOBICASH', 'Mobicash'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Espèces'), ('VISA', 'Carte Visa')], max_length=20),
        ),
    ]
