# Generated by Django 5.2.8 on 2026-04-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0004_add_coupon_fields'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='marketplace.booklisting', verbose_name='Offre vendeur'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='marketplace.suborder', verbose_name='Sous-commande'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Vendeur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('PARTIAL', 'Partiellement livré'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
    ]
