# Generated by Django 6.0.3 on 2026-05-23 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_coupon_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='bamboo_response',
            field=models.JSONField(blank=True, default=dict, help_text='Dernière réponse brute Bamboo Pay'),
        ),
        migrations.AddField(
            model_name='payment',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Date de finalisation (success/failed/expired)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(db_index=True, help_text='Référence Bamboo Pay (bamboo_ref)', max_length=128, unique=True),
        ),
    ]
