# Generated by Django 5.2.8 on 2026-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_listing_orderitem_sub_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_agent_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
