# Generated by Django 6.0.3 on 2026-05-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_options_payment_bamboo_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MOBICASH', 'Moov Money'), ('AIRTEL', 'Airtel Money'), ('CASH', 'Espèces'), ('VISA', 'Carte Visa')], max_length=20),
        ),
    ]
