# Generated by Django 6.0.5 on 2026-06-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_shipping_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='format_purchased',
            field=models.CharField(choices=[('PAPIER', 'Papier'), ('EBOOK', 'Ebook')], default='PAPIER', help_text='Format effectivement acheté (papier ou ebook)', max_length=10, verbose_name='Format acheté'),
        ),
    ]
