# Generated by Django 6.0.3 on 2026-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderevent',
            new_name='orders_orde_order_i_974e12_idx',
            old_name='orders_order_order_i_idx',
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
