# Generated by Django 5.2.8 on 2026-04-18 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_client_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('PARTIAL', 'Partiellement livré'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(choices=[('DAMAGED', 'Produit endommagé'), ('WRONG_ITEM', 'Mauvais article'), ('NOT_RECEIVED', 'Non reçu'), ('QUALITY', 'Qualité insatisfaisante'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandé'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('PROCESSED', 'Traité')], db_index=True, default='REQUESTED', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
