# Generated by Django 5.2.8 on 2026-04-28 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('categorize', 'Catégorisation livre'), ('description', 'Génération description'), ('back_cover', '4e de couverture'), ('summary', 'Résumé livre'), ('reviews_synthesis', 'Synthèse avis'), ('manuscript_analysis', 'Analyse manuscrit'), ('semantic_search', 'Recherche sémantique'), ('recommendation', 'Recommandation'), ('cross_sell', 'Cross-sell'), ('moderation', 'Modération'), ('discussion_summary', 'Résumé discussion'), ('discussion_questions', 'Questions discussion'), ('spoiler_detection', 'Détection spoiler'), ('meeting_summary', 'Résumé séance'), ('chatbot', 'Chatbot'), ('contact_classify', 'Classification contact'), ('newsletter', 'Newsletter'), ('bio', 'Bio profil'), ('price_suggest', 'Suggestion prix'), ('vendor_trends', 'Tendances vendeur'), ('stock_predict', 'Prévision stock'), ('library_recommend', 'Recommandation bibliothèque'), ('other', 'Autre')], db_index=True, max_length=30)),
                ('input_text', models.TextField(help_text='Message envoyé à Claude (tronqué si long)')),
                ('output_text', models.TextField(help_text='Réponse de Claude')),
                ('model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=60)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, help_text='Ex: book, manuscript, club', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Génération IA',
                'verbose_name_plural': 'Générations IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
