# Generated by Django 5.2.8 on 2025-12-02 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name="Photo de l'auteur")),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='Slug')),
                ('reference', models.CharField(help_text='ISBN ou code interne unique', max_length=50, unique=True, verbose_name='Référence (ISBN/Code)')),
                ('description', models.TextField(verbose_name='Description/Résumé')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (FCFA)')),
                ('format', models.CharField(choices=[('EBOOK', 'Ebook'), ('PAPIER', 'Papier')], default='PAPIER', max_length=10, verbose_name='Format')),
                ('cover_image', models.ImageField(upload_to='books/covers/', verbose_name='Image de couverture')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.author', verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'), models.Index(fields=['reference'], name='books_book_referen_c4a7e9_idx'), models.Index(fields=['available'], name='books_book_availab_3817f0_idx')],
            },
        ),
    ]
