# Generated by Django 5.2.8 on 2025-12-03 10:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Cocher pour mettre en avant ce livre', verbose_name='Best-seller'),
        ),
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix avant promotion. Laissez vide si pas de promotion.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'origine (FCFA)"),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Note sur 5 (ex: 4.5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total d'avis reçus", verbose_name="Nombre d'avis"),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_bestseller'], name='books_book_is_best_eca407_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['rating'], name='books_book_rating_d06a65_idx'),
        ),
    ]
