# Generated by Django (champ PDF pour ebooks)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(
                blank=True,
                help_text='PDF du livre pour lecture en ligne ou achat ebook.',
                null=True,
                upload_to='books/pdfs/',
                verbose_name='Fichier PDF (ebook)',
            ),
        ),
    ]
