# Generated by Django 5.2.8 on 2026-04-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_back_cover_image'),
        ('organizations', '0003_extend_org_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher_organization',
            field=models.ForeignKey(blank=True, help_text="Maison d'édition qui a publié ce livre.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_books', to='organizations.organization', verbose_name='Organisation éditrice'),
        ),
    ]
