# Generated by Django 5.2.14 on 2026-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_back_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher dans la selection editoriale sur la page d'accueil", verbose_name='Selection de la maison'),
        ),
        migrations.AddField(
            model_name='book',
            name='popularity_score',
            field=models.FloatField(default=0, help_text='Calcule automatiquement (ventes + notes + wishlist). Ne pas modifier.', verbose_name='Score de popularite'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text="Date reelle de publication du livre (pas la date d'ajout en BDD)", null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='trending_score',
            field=models.FloatField(default=0, help_text='Velocite recente. Calcule automatiquement.', verbose_name='Score tendance'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_featured'], name='books_book_is_feat_81be5a_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-popularity_score'], name='books_book_popular_6ae741_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-trending_score'], name='books_book_trendin_afec0f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-published_date'], name='books_book_publish_680bd8_idx'),
        ),
    ]
