# Generated by Django 5.2.14 on 2026-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_is_featured_book_popularity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description/Résumé'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='ISBN ou code interne unique', max_length=50, unique=True, verbose_name='Référence (ISBN/Code)'),
        ),
    ]
