# Generated by Django 5.2.8 on 2026-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_add_publisher_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total d'exemplaires vendus (mis à jour au paiement).", verbose_name='Ventes totales'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Calculé automatiquement : 10+ ventes ou top 10%.', verbose_name='Best-seller'),
        ),
    ]
