# Generated by Django 5.2.14 on 2026-05-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_description_alter_book_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total d'exemplaires vendus", verbose_name='Ventes totales'),
        ),
    ]
