# Generated by Django 6.0.3 on 2026-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reference',
            field=models.CharField(blank=True, help_text='ISBN ou code interne unique', max_length=50, null=True, unique=True, verbose_name='Référence (ISBN/Code)'),
        ),
    ]
