# Generated by Django 5.2.14 on 2026-05-26 22:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_fix_reference_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF du livre pour lecture en ligne ou achat ebook.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='books/pdfs/', verbose_name='Fichier PDF (ebook)'),
        ),
    ]
