# Generated by Django 5.2.14 on 2026-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dimensions_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hauteur (cm)'),
        ),
        migrations.AddField(
            model_name='book',
            name='dimensions_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Largeur (cm)'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN-13 standard', max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('AR', 'Arabe'), ('PT', 'Portugais'), ('ES', 'Espagnol'), ('AUTRE', 'Autre')], default='FR', max_length=10, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids (g)'),
        ),
    ]
