# Generated by Django 6.0.5 on 2026-06-22 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_collection_book_excerpt_pdf_book_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de la version ebook (requis si ebook active)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix ebook (FCFA)'),
        ),
        migrations.AddField(
            model_name='book',
            name='has_ebook',
            field=models.BooleanField(default=False, help_text='Le livre est-il aussi disponible en format ebook ?', verbose_name='Disponible en ebook'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix papier (FCFA)'),
        ),
    ]
