# Generated by Django 5.2.8 on 2026-03-07 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reduction (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reduction fixe (FCFA)')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valide a partir de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'a")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre max d'utilisations")),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Utilisations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
