# Generated by Django 6.0.3 on 2026-04-13 — Phase 1: add new fields + CouponTemplate (keep old fields)

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0009_coupon_template_and_coupon_v2'),
        ('organizations', '0004_account_deletion_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # New fields on Coupon (old discount_percent/discount_amount kept for now)
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='custom_message',
            field=models.TextField(blank=True, verbose_name='Message personnalisé'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe (FCFA)'), ('FREE_SHIPPING', 'Livraison offerte')], default='PERCENT', max_length=20, verbose_name='Type de réduction'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum (FCFA)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='organizations.organization', verbose_name='Organisation émettrice'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire (user)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email destinataire'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('PENDING', "En attente d'envoi"), ('SENT', 'Envoyé'), ('USED', 'Utilisé'), ('EXPIRED', 'Expiré'), ('REVOKED', 'Révoqué'), ('FAILED', "Échec d'envoi")], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_on_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_coupons', to='orders.order', verbose_name='Utilisé sur commande'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name="Nombre max d'utilisations"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valide à partir de'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'à"),
        ),
        # CouponTemplate model
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du template')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Pourcentage'), ('FIXED', 'Montant fixe (FCFA)'), ('FREE_SHIPPING', 'Livraison offerte')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum de commande (FCFA)')),
                ('default_expiry_days', models.PositiveIntegerField(default=30, verbose_name='Expiration par défaut (jours)')),
                ('description_for_email', models.TextField(blank=True, verbose_name="Description pour l'email")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupon_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_templates', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Template coupon',
                'verbose_name_plural': 'Templates coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='coupons.coupontemplate', verbose_name='Template source'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'recipient'], name='coupons_cou_status_dc85cf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['organization', 'status'], name='coupons_cou_organiz_a017bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['recipient_email'], name='coupons_cou_recipie_3e4b6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coupontemplate',
            unique_together={('organization', 'name')},
        ),
    ]
