# Generated by Django 6.0.3 on 2026-04-13 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_remove_old_discount_fields'),
        ('orders', '0009_coupon_template_and_coupon_v2'),
        ('organizations', '0004_account_deletion_set_null'),
        ('users', '0014_account_deletion_set_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupontemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coupon',
            name='provider_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile_type__in': ['CORRECTEUR', 'ILLUSTRATEUR', 'TRADUCTEUR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='users.userprofile', verbose_name='Profil prestataire émetteur'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='provider_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile_type__in': ['CORRECTEUR', 'ILLUSTRATEUR', 'TRADUCTEUR']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_templates', to='users.userprofile', verbose_name='Profil prestataire'),
        ),
        migrations.AlterField(
            model_name='coupontemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_templates', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['provider_profile', 'status'], name='coupons_cou_provide_4d4a13_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('provider_profile__isnull', False), _negated=True), name='coupon_emitter_xor'),
        ),
        migrations.AddConstraint(
            model_name='coupontemplate',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('provider_profile__isnull', False), _negated=True), name='coupontemplate_emitter_xor'),
        ),
        migrations.AddConstraint(
            model_name='coupontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='coupontemplate_unique_org_name'),
        ),
        migrations.AddConstraint(
            model_name='coupontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_profile__isnull', False)), fields=('provider_profile', 'name'), name='coupontemplate_unique_provider_name'),
        ),
    ]
