# Generated by Django 6.0.3 on 2026-04-13 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_verify_emitter_xor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontemplate',
            name='accent_color',
            field=models.CharField(default='#5b5eea', max_length=7, verbose_name="Couleur d'accent"),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='category',
            field=models.CharField(choices=[('BIENVENUE', 'Bienvenue'), ('FIDELITE', 'Fidélité'), ('SAISONNIER', 'Saisonnier'), ('REACTIVATION', 'Réactivation'), ('ANNIVERSAIRE', 'Anniversaire'), ('FLASH', 'Flash'), ('PARRAINAGE', 'Parrainage'), ('PROMO_PRODUIT', 'Promo produit'), ('DESTOCKAGE', 'Déstockage'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='clone_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de clonages'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='coupons.coupontemplate', verbose_name='Cloné depuis'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='commercial_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre commercial'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='display_order',
            field=models.PositiveIntegerField(default=100, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='first_order_only',
            field=models.BooleanField(default=False, verbose_name='Premier achat uniquement'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='icon',
            field=models.CharField(default='fas fa-ticket-alt', max_length=50, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Template système Frollot'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='marketing_description',
            field=models.TextField(blank=True, verbose_name='Description marketing'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plafond de réduction (FCFA)'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='min_customer_age_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancienneté client minimum (jours)'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='per_customer_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite par client'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='quota_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Coupons déjà émis'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sous-titre accroche'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='system_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Slug système'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='target_emitter_type',
            field=models.CharField(choices=[('ALL', 'Tous'), ('ORGANIZATION', 'Organisations uniquement'), ('PROVIDER_PROFILE', 'Prestataires uniquement')], default='ALL', max_length=20, verbose_name="Type d'émetteur cible"),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='total_quota',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quota total de coupons'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de validité du template'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de validité du template'),
        ),
        migrations.AlterField(
            model_name='coupontemplate',
            name='description_for_email',
            field=models.TextField(blank=True, verbose_name="Description pour l'email (obsolète)"),
        ),
        migrations.AlterField(
            model_name='coupontemplate',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom interne'),
        ),
    ]
