# Generated by Django 6.0.3 on 2026-04-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_migrate_description_to_marketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupontemplate',
            name='description_for_email',
        ),
    ]
