"""Seed de la bibliothèque système : 30 templates de coupons prêts à l'emploi."""
from decimal import Decimal
from django.db import migrations


SYSTEM_TEMPLATES = [
    # ── BIENVENUE (3) — fa-hand-holding-heart, #22c55e ──
    {
        'system_slug': 'bienvenue-15',
        'name': 'Bienvenue 15%',
        'commercial_title': 'Bienvenue chez Frollot !',
        'subtitle': '15% sur votre première commande',
        'marketing_description': 'Profitez de 15% de réduction sur votre toute première commande. Découvrez notre catalogue avec un avantage exclusif réservé aux nouveaux clients.',
        'category': 'BIENVENUE',
        'icon': 'fas fa-hand-holding-heart',
        'accent_color': '#22c55e',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('15'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 10,
    },
    {
        'system_slug': 'bienvenue-2000',
        'name': 'Bienvenue 2000 FCFA',
        'commercial_title': 'Cadeau de bienvenue',
        'subtitle': '2 000 FCFA offerts pour votre premier achat',
        'marketing_description': '2 000 FCFA de réduction immédiate sur votre première commande. Un petit geste pour bien commencer.',
        'category': 'BIENVENUE',
        'icon': 'fas fa-hand-holding-heart',
        'accent_color': '#22c55e',
        'discount_type': 'FIXED',
        'discount_value': Decimal('2000'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 11,
    },
    {
        'system_slug': 'bienvenue-livraison',
        'name': 'Bienvenue livraison offerte',
        'commercial_title': 'Livraison offerte — Premier achat',
        'subtitle': 'Votre première commande livrée gratuitement',
        'marketing_description': 'Offrez la livraison à vos nouveaux clients pour leur toute première commande.',
        'category': 'BIENVENUE',
        'icon': 'fas fa-hand-holding-heart',
        'accent_color': '#22c55e',
        'discount_type': 'FREE_SHIPPING',
        'discount_value': Decimal('0'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 12,
    },
    # ── FIDELITE (4) — fa-crown, #eab308 ──
    {
        'system_slug': 'fidelite-10',
        'name': 'Fidélité 10%',
        'commercial_title': 'Merci pour votre fidélité',
        'subtitle': '10% de réduction pour nos clients fidèles',
        'marketing_description': 'Un geste de reconnaissance pour nos clients de plus de 6 mois. Profitez de 10% sur votre prochaine commande.',
        'category': 'FIDELITE',
        'icon': 'fas fa-crown',
        'accent_color': '#eab308',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('10'),
        'min_customer_age_days': 180,
        'default_expiry_days': 60,
        'target_emitter_type': 'ALL',
        'display_order': 20,
    },
    {
        'system_slug': 'fidelite-15',
        'name': 'Fidélité premium 15%',
        'commercial_title': 'Client privilégié',
        'subtitle': '15% exclusifs pour nos fidèles d\'un an',
        'marketing_description': '15% de réduction réservés à nos clients les plus fidèles, inscrits depuis plus d\'un an.',
        'category': 'FIDELITE',
        'icon': 'fas fa-crown',
        'accent_color': '#eab308',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('15'),
        'min_customer_age_days': 365,
        'default_expiry_days': 45,
        'target_emitter_type': 'ALL',
        'display_order': 21,
    },
    {
        'system_slug': 'fidelite-5000',
        'name': 'Fidélité 5000 FCFA',
        'commercial_title': 'Bonus fidélité',
        'subtitle': '5 000 FCFA pour vous remercier',
        'marketing_description': '5 000 FCFA de réduction pour remercier vos clients fidèles de plus de 3 mois.',
        'category': 'FIDELITE',
        'icon': 'fas fa-crown',
        'accent_color': '#eab308',
        'discount_type': 'FIXED',
        'discount_value': Decimal('5000'),
        'min_customer_age_days': 90,
        'default_expiry_days': 60,
        'target_emitter_type': 'ALL',
        'display_order': 22,
    },
    {
        'system_slug': 'merci-avis',
        'name': 'Merci pour votre avis',
        'commercial_title': 'Merci pour votre avis !',
        'subtitle': '1 500 FCFA pour avoir partagé votre opinion',
        'marketing_description': '1 500 FCFA offerts pour remercier vos clients qui prennent le temps de laisser un avis.',
        'category': 'FIDELITE',
        'icon': 'fas fa-star',
        'accent_color': '#eab308',
        'discount_type': 'FIXED',
        'discount_value': Decimal('1500'),
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 23,
    },
    # ── SAISONNIER (5) — fa-calendar-alt, #f97316 ──
    {
        'system_slug': 'black-friday-30',
        'name': 'Black Friday -30%',
        'commercial_title': 'Black Friday -30%',
        'subtitle': '-30% sur tout le catalogue',
        'marketing_description': '-30% sur tout le catalogue pendant le Black Friday ! Offre limitée à 3 jours.',
        'category': 'SAISONNIER',
        'icon': 'fas fa-calendar-alt',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('30'),
        'default_expiry_days': 3,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 30,
    },
    {
        'system_slug': 'black-friday-50',
        'name': 'Black Friday Premium -50%',
        'commercial_title': 'Black Friday Premium',
        'subtitle': '-50% plafonné à 10 000 FCFA — 48h chrono',
        'marketing_description': '-50% plafonné à 10 000 FCFA. Offre exceptionnelle de 48 heures pour le Black Friday.',
        'category': 'SAISONNIER',
        'icon': 'fas fa-calendar-alt',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('50'),
        'max_discount_amount': Decimal('10000'),
        'default_expiry_days': 2,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 31,
    },
    {
        'system_slug': 'noel-20',
        'name': 'Noël -20%',
        'commercial_title': 'Joyeuses fêtes',
        'subtitle': '-20% pour préparer vos cadeaux littéraires',
        'marketing_description': '-20% sur tout le catalogue pour préparer vos cadeaux de Noël. Offre valable 2 semaines.',
        'category': 'SAISONNIER',
        'icon': 'fas fa-gift',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('20'),
        'default_expiry_days': 14,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 32,
    },
    {
        'system_slug': 'rentree-litteraire',
        'name': 'Rentrée littéraire',
        'commercial_title': 'Rentrée littéraire',
        'subtitle': '-15% pour découvrir les nouveautés',
        'marketing_description': '-15% à l\'occasion de la rentrée littéraire. Découvrez les nouveaux titres de la saison.',
        'category': 'SAISONNIER',
        'icon': 'fas fa-calendar-alt',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('15'),
        'default_expiry_days': 21,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 33,
    },
    {
        'system_slug': 'saint-valentin',
        'name': 'Saint-Valentin',
        'commercial_title': 'Offrez un livre d\'amour',
        'subtitle': '3 000 FCFA pour la Saint-Valentin',
        'marketing_description': '3 000 FCFA offerts pour la Saint-Valentin. Offrez un livre à la personne que vous aimez.',
        'category': 'SAISONNIER',
        'icon': 'fas fa-heart',
        'accent_color': '#f97316',
        'discount_type': 'FIXED',
        'discount_value': Decimal('3000'),
        'default_expiry_days': 7,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 34,
    },
    # ── REACTIVATION (2) — fa-heart, #ec4899 ──
    {
        'system_slug': 'reactivation-20',
        'name': 'Réactivation -20%',
        'commercial_title': 'Vous nous manquez !',
        'subtitle': '-20% pour votre retour parmi nous',
        'marketing_description': '-20% de réduction pour souhaiter un bon retour à vos clients inactifs. Ravivez la flamme.',
        'category': 'REACTIVATION',
        'icon': 'fas fa-heart',
        'accent_color': '#ec4899',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('20'),
        'default_expiry_days': 14,
        'target_emitter_type': 'ALL',
        'display_order': 40,
    },
    {
        'system_slug': 'reactivation-livraison',
        'name': 'Réactivation livraison',
        'commercial_title': 'Retour en douceur',
        'subtitle': 'Livraison offerte pour fêter votre retour',
        'marketing_description': 'Livraison gratuite pour encourager vos clients à revenir. Un geste simple et efficace.',
        'category': 'REACTIVATION',
        'icon': 'fas fa-heart',
        'accent_color': '#ec4899',
        'discount_type': 'FREE_SHIPPING',
        'discount_value': Decimal('0'),
        'default_expiry_days': 14,
        'target_emitter_type': 'ALL',
        'display_order': 41,
    },
    # ── ANNIVERSAIRE (2) — fa-birthday-cake, #8b5cf6 ──
    {
        'system_slug': 'anniversaire-livraison',
        'name': 'Anniversaire livraison',
        'commercial_title': 'Joyeux anniversaire !',
        'subtitle': 'Livraison offerte pour votre jour spécial',
        'marketing_description': 'Offrez la livraison à vos clients pour leur anniversaire. Un petit cadeau qui fait plaisir.',
        'category': 'ANNIVERSAIRE',
        'icon': 'fas fa-birthday-cake',
        'accent_color': '#8b5cf6',
        'discount_type': 'FREE_SHIPPING',
        'discount_value': Decimal('0'),
        'default_expiry_days': 7,
        'target_emitter_type': 'ALL',
        'display_order': 50,
    },
    {
        'system_slug': 'anniversaire-10',
        'name': 'Anniversaire -10%',
        'commercial_title': 'Cadeau d\'anniversaire',
        'subtitle': '-10% pour célébrer votre jour spécial',
        'marketing_description': '-10% en cadeau pour l\'anniversaire de vos clients. Une attention qui renforce la fidélité.',
        'category': 'ANNIVERSAIRE',
        'icon': 'fas fa-birthday-cake',
        'accent_color': '#8b5cf6',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('10'),
        'default_expiry_days': 7,
        'target_emitter_type': 'ALL',
        'display_order': 51,
    },
    # ── FLASH (3) — fa-bolt, #f43f5e ──
    {
        'system_slug': 'flash-25-24h',
        'name': 'Flash 25% 24h',
        'commercial_title': 'Vente flash 24h',
        'subtitle': '-25% pendant 24 heures seulement',
        'marketing_description': '-25% pendant 24 heures seulement. Ne ratez pas cette offre éclair.',
        'category': 'FLASH',
        'icon': 'fas fa-bolt',
        'accent_color': '#f43f5e',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('25'),
        'default_expiry_days': 1,
        'target_emitter_type': 'ALL',
        'display_order': 60,
    },
    {
        'system_slug': 'flash-40-12h',
        'name': 'Flash 40% 12h',
        'commercial_title': 'Méga flash 12h',
        'subtitle': '-40% plafonné à 8 000 FCFA — 12h chrono',
        'marketing_description': '-40% plafonné à 8 000 FCFA. 12 heures pour en profiter. L\'offre la plus agressive de votre catalogue.',
        'category': 'FLASH',
        'icon': 'fas fa-bolt',
        'accent_color': '#f43f5e',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('40'),
        'max_discount_amount': Decimal('8000'),
        'default_expiry_days': 1,
        'target_emitter_type': 'ALL',
        'display_order': 61,
    },
    {
        'system_slug': 'flash-livraison-48h',
        'name': 'Flash livraison 48h',
        'commercial_title': 'Livraison offerte 48h',
        'subtitle': 'Livraison gratuite pendant 48 heures',
        'marketing_description': 'Livraison gratuite pendant 48 heures. Idéal pour booster les ventes sur un week-end.',
        'category': 'FLASH',
        'icon': 'fas fa-bolt',
        'accent_color': '#f43f5e',
        'discount_type': 'FREE_SHIPPING',
        'discount_value': Decimal('0'),
        'default_expiry_days': 2,
        'target_emitter_type': 'ALL',
        'display_order': 62,
    },
    # ── PARRAINAGE (2) — fa-gift, #6366f1 ──
    {
        'system_slug': 'parrainage-5000',
        'name': 'Parrainage 5000 FCFA',
        'commercial_title': 'Parrainage ami',
        'subtitle': '5 000 FCFA offerts à votre filleul',
        'marketing_description': '5 000 FCFA offerts au filleul pour sa première commande. Un cadeau qui élargit votre clientèle.',
        'category': 'PARRAINAGE',
        'icon': 'fas fa-gift',
        'accent_color': '#6366f1',
        'discount_type': 'FIXED',
        'discount_value': Decimal('5000'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 70,
    },
    {
        'system_slug': 'parrainage-10',
        'name': 'Parrainage 10%',
        'commercial_title': 'Parrainage -10%',
        'subtitle': '-10% pour chaque ami parrainé',
        'marketing_description': '-10% de réduction pour chaque ami parrainé sur sa première commande.',
        'category': 'PARRAINAGE',
        'icon': 'fas fa-gift',
        'accent_color': '#6366f1',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('10'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'ALL',
        'display_order': 71,
    },
    # ── PROMO_PRODUIT (2) — fa-tag, #0ea5e9 ──
    {
        'system_slug': 'promo-jeunesse',
        'name': 'Promo jeunesse',
        'commercial_title': 'Spécial jeunesse',
        'subtitle': '-20% sur la sélection jeunesse',
        'marketing_description': '-20% sur notre sélection jeunesse et bandes dessinées. Encouragez la lecture chez les jeunes.',
        'category': 'PROMO_PRODUIT',
        'icon': 'fas fa-tag',
        'accent_color': '#0ea5e9',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('20'),
        'default_expiry_days': 14,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 80,
    },
    {
        'system_slug': 'promo-education',
        'name': 'Promo éducation',
        'commercial_title': 'Éducation & savoir',
        'subtitle': '-15% sur les manuels et ouvrages éducatifs',
        'marketing_description': '-15% sur les manuels scolaires et ouvrages éducatifs. Investissez dans le savoir.',
        'category': 'PROMO_PRODUIT',
        'icon': 'fas fa-tag',
        'accent_color': '#0ea5e9',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('15'),
        'default_expiry_days': 21,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 81,
    },
    # ── DESTOCKAGE (2) — fa-fire, #f97316 ──
    {
        'system_slug': 'destockage-40',
        'name': 'Déstockage -40%',
        'commercial_title': 'Déstockage -40%',
        'subtitle': '-40% sur une sélection à prix cassé',
        'marketing_description': '-40% sur une sélection d\'ouvrages en déstockage. Faites de la place pour les nouveautés.',
        'category': 'DESTOCKAGE',
        'icon': 'fas fa-fire',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('40'),
        'default_expiry_days': 7,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 90,
    },
    {
        'system_slug': 'destockage-60',
        'name': 'Liquidation totale',
        'commercial_title': 'Liquidation totale',
        'subtitle': 'Jusqu\'à -60% sur les derniers exemplaires',
        'marketing_description': 'Jusqu\'à -60% sur les derniers exemplaires disponibles. Plafonné à 15 000 FCFA.',
        'category': 'DESTOCKAGE',
        'icon': 'fas fa-fire',
        'accent_color': '#f97316',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('60'),
        'max_discount_amount': Decimal('15000'),
        'default_expiry_days': 5,
        'target_emitter_type': 'ORGANIZATION',
        'display_order': 91,
    },
    # ── PROVIDER_PROFILE (5) — Prestataires de services ──
    {
        'system_slug': 'correction-premier-projet',
        'name': 'Correction premier projet',
        'commercial_title': 'Correction -15% premier projet',
        'subtitle': '-15% sur votre première correction',
        'marketing_description': '-15% de réduction sur le premier projet de correction. Idéal pour convaincre de nouveaux auteurs.',
        'category': 'BIENVENUE',
        'icon': 'fas fa-certificate',
        'accent_color': '#14b8a6',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('15'),
        'first_order_only': True,
        'default_expiry_days': 30,
        'target_emitter_type': 'PROVIDER_PROFILE',
        'display_order': 100,
    },
    {
        'system_slug': 'pack-3-projets',
        'name': 'Pack 3 projets',
        'commercial_title': 'Pack 3 projets -10%',
        'subtitle': '-10% pour fidéliser vos clients réguliers',
        'marketing_description': '-10% de réduction pour encourager vos clients à revenir sur plusieurs projets.',
        'category': 'FIDELITE',
        'icon': 'fas fa-trophy',
        'accent_color': '#14b8a6',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('10'),
        'min_customer_age_days': 30,
        'default_expiry_days': 60,
        'target_emitter_type': 'PROVIDER_PROFILE',
        'display_order': 101,
    },
    {
        'system_slug': 'delai-express-offert',
        'name': 'Délai express offert',
        'commercial_title': 'Délai express offert',
        'subtitle': 'Livraison express offerte sur votre prochain projet',
        'marketing_description': 'Offrez la livraison express à votre client sur son prochain projet. Un geste commercial apprécié.',
        'category': 'FLASH',
        'icon': 'fas fa-bolt',
        'accent_color': '#14b8a6',
        'discount_type': 'FREE_SHIPPING',
        'discount_value': Decimal('0'),
        'default_expiry_days': 14,
        'target_emitter_type': 'PROVIDER_PROFILE',
        'display_order': 102,
    },
    {
        'system_slug': 'illustration-couverture-20',
        'name': 'Illustration couverture -20%',
        'commercial_title': 'Illustration couverture -20%',
        'subtitle': '-20% sur une illustration de couverture',
        'marketing_description': '-20% sur une prestation d\'illustration de couverture. Attirez de nouveaux auteurs avec cette offre.',
        'category': 'PROMO_PRODUIT',
        'icon': 'fas fa-award',
        'accent_color': '#14b8a6',
        'discount_type': 'PERCENT',
        'discount_value': Decimal('20'),
        'default_expiry_days': 21,
        'target_emitter_type': 'PROVIDER_PROFILE',
        'display_order': 103,
    },
    {
        'system_slug': 'traduction-2000',
        'name': 'Traduction -2000 FCFA',
        'commercial_title': 'Traduction -2 000 FCFA',
        'subtitle': '2 000 FCFA de réduction sur une traduction',
        'marketing_description': '2 000 FCFA de réduction sur une prestation de traduction. Proposez cette offre à vos prospects.',
        'category': 'PROMO_PRODUIT',
        'icon': 'fas fa-award',
        'accent_color': '#14b8a6',
        'discount_type': 'FIXED',
        'discount_value': Decimal('2000'),
        'default_expiry_days': 30,
        'target_emitter_type': 'PROVIDER_PROFILE',
        'display_order': 104,
    },
]


def seed_system_templates(apps, schema_editor):
    CouponTemplate = apps.get_model('coupons', 'CouponTemplate')
    for tpl_data in SYSTEM_TEMPLATES:
        slug = tpl_data['system_slug']
        defaults = {**tpl_data, 'is_system': True, 'is_published': True}
        CouponTemplate.objects.get_or_create(system_slug=slug, defaults=defaults)


def remove_system_templates(apps, schema_editor):
    CouponTemplate = apps.get_model('coupons', 'CouponTemplate')
    CouponTemplate.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_remove_description_for_email'),
    ]

    operations = [
        migrations.RunPython(seed_system_templates, remove_system_templates),
    ]
