# Generated by Django 6.0.3 on 2026-05-21 09:18

import apps.newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmation_token',
            field=models.CharField(default=apps.newsletter.models._default_token, max_length=32, verbose_name='Token de confirmation'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmé'),
        ),
    ]
