# Generated by Django 5.2.8 on 2026-04-18 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de confirmation'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmé'),
        ),
    ]
