# Generated by Django 6.0.3 on 2026-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_add_confirmation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmé'),
        ),
    ]
