# Generated by Django 5.2.8 on 2026-04-04 17:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0010_userprofile_avg_rating_userprofile_avg_response_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepted_genres',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['ROMAN', 'POESIE', 'ESSAI']", verbose_name='Genres acceptés'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='organization',
            name='avg_response_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps de réponse moyen (jours)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_accepting_manuscripts',
            field=models.BooleanField(default=False, verbose_name='Accepte les manuscrits'),
        ),
        migrations.AddField(
            model_name='organization',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
        migrations.AddField(
            model_name='organization',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="Domaines d'expertise. Ex: ['Littérature africaine', 'Romans policiers']", verbose_name='Spécialités'),
        ),
        migrations.AddField(
            model_name='organization',
            name='submission_guidelines',
            field=models.TextField(blank=True, help_text='Instructions affichées sur la vitrine pour les auteurs souhaitant soumettre.', verbose_name='Guide de soumission'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiries/', verbose_name='Pièce jointe')),
                ('response', models.TextField(blank=True, verbose_name='Réponse')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ANSWERED', 'Répondu'), ('CLOSED', 'Fermé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_responses', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('target_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to='organizations.organization', verbose_name='Organisation cible')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to='users.userprofile', verbose_name='Professionnel cible')),
            ],
            options={
                'verbose_name': 'Demande de renseignement',
                'verbose_name_plural': 'Demandes de renseignement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organizations.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis sur organisation',
                'verbose_name_plural': 'Avis sur organisations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
