# Generated by Django 5.2.8 on 2026-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_accepted_genres_organization_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepted_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='Langues acceptées pour les manuscrits'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"lundi":{"open":"08:00","close":"17:00"},...}', verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='organization',
            name='editorial_line',
            field=models.TextField(blank=True, verbose_name='Ligne éditoriale'),
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de création'),
        ),
        migrations.AddField(
            model_name='organization',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['FR', 'EN', 'AR']", verbose_name='Langues de travail'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['CASH','MOBILE_MONEY','CARD','VIREMENT']", verbose_name='Moyens de paiement'),
        ),
        migrations.AddField(
            model_name='organization',
            name='po_box',
            field=models.CharField(blank=True, max_length=50, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='organization',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['MANUSCRIT','SYNOPSIS','LETTRE_MOTIVATION','CV','PHOTO']", verbose_name='Documents requis'),
        ),
        migrations.AddField(
            model_name='organization',
            name='response_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Délai maximum promis pour examiner un manuscrit.', null=True, verbose_name='Délai de réponse manuscrits (jours)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_description',
            field=models.CharField(blank=True, help_text='Phrase courte affichée sur les cartes (max 280 car.).', max_length=280, verbose_name='Accroche'),
        ),
        migrations.AddField(
            model_name='organization',
            name='simultaneous_submissions',
            field=models.BooleanField(default=True, verbose_name='Soumissions simultanées autorisées'),
        ),
        migrations.AddField(
            model_name='organization',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='{"facebook":"...","instagram":"...","twitter":"...","linkedin":"...","youtube":"..."}', verbose_name='Réseaux sociaux'),
        ),
        migrations.AddField(
            model_name='organization',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text="Ex: ['ADULTE','JEUNESSE','UNIVERSITAIRE']", verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type_specific_data',
            field=models.JSONField(blank=True, default=dict, help_text="Champs dynamiques selon le type d'organisation.", verbose_name='Données spécifiques au type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
