# Generated by Django 6.0.3 on 2026-04-11 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_extend_org_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='organizationreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
