# Generated by Django 5.2.8 on 2026-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_account_deletion_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email invité'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Déclinée'), ('EXPIRED', 'Expirée')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('MAISON_EDITION', "Maison d'édition"), ('LIBRAIRIE', 'Librairie'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('IMPRIMERIE', 'Imprimerie')], db_index=True, max_length=20, verbose_name="Type d'organisation"),
        ),
    ]
